INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('509', 'The Nobel Peace Prize', 'for their pioneering work in the international peace movement and compassionate effort to relieve human suffering, thereby promoting the fraternity between nations', 146115, '1947-10-30');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('537', 'The Nobel Peace Prize', 'for worldwide respect for human rights', 700000, '1977-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('881', 'The Nobel Peace Prize', 'for over six decades contributed to the advancement of peace and reconciliation, democracy and human rights in Europe', 8000000, '2012-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('508', 'The Nobel Peace Prize', 'for their pioneering work in the international peace movement and compassionate effort to relieve human suffering, thereby promoting the fraternity between nations', 146115, '1947-10-30');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('810', 'The Nobel Peace Prize', 'for their efforts to create economic and social development from below', 10000000, '2006-10-13');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('467', 'The Nobel Peace Prize', 'for its striving in public law to develop peaceful ties between nations and to make the laws of war more humane', 140859, '1904-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('818', 'The Nobel Peace Prize', 'for their efforts to build up and disseminate greater knowledge about man-made climate change, and to lay the foundations for the measures that are needed to counteract such change', 10000000, '2007-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('797', 'The Nobel Peace Prize', 'for their efforts to prevent nuclear energy from being used for military purposes and to ensure that nuclear energy for peaceful purposes is used in the safest possible way', 10000000, '2005-10-07');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('948', 'The Nobel Peace Prize', 'for its work to draw attention to the catastrophic humanitarian consequences of any use of nuclear weapons and for its ground-breaking efforts to achieve a treaty-based prohibition of such weapons', 9000000, '2017-10-06');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('564', 'The Nobel Peace Prize', 'for their efforts to ban and remove anti-personnel landmines', 7500000, '1997-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('482', 'The Nobel Peace Prize', 'for the efforts to take care of wounded soldiers and prisoners of war and their families', 133823, '1917-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('527', 'The Nobel Peace Prize', 'for creating international legislation insuring certain norms for working conditions in every country', 375000, '1969-10-20');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('547', 'The Nobel Peace Prize', 'for spreading authoritative information and by creating awareness of the catastrophic consequences of  nuclear  war', 1800000, '1985-10-05');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('523', 'The Nobel Peace Prize', 'for promoting the principles of the Geneva Convention and cooperation with the UN', 265000, '1963-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('568', 'The Nobel Peace Prize', 'in recognition of the organisations pioneering humanitarian work on several continents', 7900000, '1999-10-15');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('503', 'The Nobel Peace Prize', 'for having carried on the work of Fridtjof Nansen to the benefit of refugees across Europe', 155077, '1938-11-17');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('925', 'The Nobel Peace Prize', 'for its decisive contribution to the building of a pluralistic democracy in Tunisia in the wake of the Jasmine Revolution of 2011', 8000000, '2015-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('515', 'The Nobel Peace Prize', 'for its efforts to heal the wounds of war by providing help and protection to refugees all over the world', 181647, '1955-11-05');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('893', 'The Nobel Peace Prize', 'for its extensive efforts to eliminate chemical weapons', 8000000, '2013-10-11');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('477', 'The Nobel Peace Prize', 'for acting as a link between the peace societies of the various countries, and helping them to organize the world rallies of the international peace movement', 140703, '1910-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('561', 'The Nobel Peace Prize', 'for their efforts to diminish the part played by nuclear arms in international politics and, in the longer run, to eliminate such arms', 7200000, '1995-10-13');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('748', 'The Nobel Peace Prize', 'for their work for a better organized and more peaceful world', 10000000, '2001-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('525', 'The Nobel Peace Prize', 'for its effort to enhance solidarity between nations and reduce the difference between rich and poor states', 282000, '1965-10-26');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('550', 'The Nobel Peace Prize', 'for preventing armed clashes and creating conditions for negotiations', 2500000, '1988-09-29');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('482', 'The Nobel Peace Prize', 'for the great work it has performed during the war on behalf of humanity', 121841, '1945-11-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('515', 'The Nobel Peace Prize', 'for promoting the fundamental rights of refugees', 1000000, '1981-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('482', 'The Nobel Peace Prize', 'for promoting the principles of the Geneva Convention and cooperation with the UN', 265000, '1963-10-10');
INSERT INTO Laureate (Id) VALUES ('509');
INSERT INTO Laureate (Id) VALUES ('537');
INSERT INTO Laureate (Id) VALUES ('881');
INSERT INTO Laureate (Id) VALUES ('508');
INSERT INTO Laureate (Id) VALUES ('810');
INSERT INTO Laureate (Id) VALUES ('467');
INSERT INTO Laureate (Id) VALUES ('818');
INSERT INTO Laureate (Id) VALUES ('797');
INSERT INTO Laureate (Id) VALUES ('948');
INSERT INTO Laureate (Id) VALUES ('564');
INSERT INTO Laureate (Id) VALUES ('482');
INSERT INTO Laureate (Id) VALUES ('527');
INSERT INTO Laureate (Id) VALUES ('547');
INSERT INTO Laureate (Id) VALUES ('523');
INSERT INTO Laureate (Id) VALUES ('568');
INSERT INTO Laureate (Id) VALUES ('503');
INSERT INTO Laureate (Id) VALUES ('925');
INSERT INTO Laureate (Id) VALUES ('515');
INSERT INTO Laureate (Id) VALUES ('893');
INSERT INTO Laureate (Id) VALUES ('477');
INSERT INTO Laureate (Id) VALUES ('561');
INSERT INTO Laureate (Id) VALUES ('748');
INSERT INTO Laureate (Id) VALUES ('525');
INSERT INTO Laureate (Id) VALUES ('550');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('509', 'American Friends Service Committee (The Quakers)', 'North America', '1917-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('537', 'Amnesty International', 'Europe', '1961-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('881', 'European Union (EU)', 'nan', '1952-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('508', 'Friends Service Council (The Quakers)', 'Europe', '1647-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('810', 'Grameen Bank', 'Asia', '1976-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('467', 'Institut de droit international', 'Europe', '1873-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('818', 'Intergovernmental Panel on Climate Change (IPCC)', 'North America', '1988-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('797', 'International Atomic Energy Agency (IAEA)', 'Europe', '1957-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('948', 'International Campaign to Abolish Nuclear Weapons (ICAN)', 'Oceania', '2007-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('564', 'International Campaign to Ban Landmines (ICBL)', 'North America', '1992-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('482', 'Comité international de la Croix Rouge', 'Europe', '1863-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('527', 'International Labour Organization (I.L.O.)', 'Europe', '1919-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('547', 'International Physicians for the Prevention of Nuclear War', 'North America', '1980-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('523', 'Ligue des Sociétés de la Croix-Rouge (League of Red Cross Societies)', 'Europe', '1919-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('568', 'Médecins Sans Frontières', 'Europe', '1971-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('503', 'Office international Nansen pour les Réfugiés (Nansen International Office for Refugees)', 'Europe', '1921-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('925', 'National Dialogue Quartet', 'nan', 'nan');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('515', 'Office of the United Nations High Commissioner for Refugees', 'Europe', '1951-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('893', 'Organisation for the Prohibition of Chemical Weapons (OPCW)', 'nan', '1997-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('477', 'Bureau international permanent de la Paix', 'Europe', '1891-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('561', 'Pugwash Conferences on Science and World Affairs', 'North America', '1957-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('748', 'United Nations (U.N.)', 'North America', '1945-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('525', 'United Nations Childrens Fund (UNICEF)', 'North America', '1946-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('550', 'United Nations Peacekeeping Forces', 'North America', '1948-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('482', 'Comité international de la Croix Rouge', 'Europe', '1863-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('515', 'Office of the United Nations High Commissioner for Refugees', 'Europe', '1951-00-00');
INSERT INTO Organisation (Id, orgName, orgCountry, dateFounded) VALUES ('482', 'Comité international de la Croix Rouge', 'Europe', '1863-00-00');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('745', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for their analyses of markets with asymmetric information', 10000000, '2001-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('102', 'The Nobel Prize in Physics', 'for the discovery of the connection between collective motion and particle motion in atomic nuclei and the development of the theory of the structure of the atomic nucleus based on this connection', 630000, '1975-10-17');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('779', 'The Nobel Prize in Chemistry', 'for the discovery of ubiquitin-mediated protein degradation', 10000000, '2004-10-06');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('259', 'The Nobel Prize in Chemistry', 'for his development of crystallographic electron microscopy and his structural elucidation of biologically important nucleic acid-protein complexes', 1150000, '1982-10-18');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('114', 'The Nobel Prize in Physics', 'for their contributions to the theory of the unified weak and electromagnetic interaction between elementary particles, including, inter alia, the prediction of the weak neutral current', 800000, '1979-10-15');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('982', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for their experimental approach to alleviating global poverty', 9000000, '2019-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('981', 'The Nobel Peace Prize', 'for his efforts to achieve peace and international cooperation, and in particular for his decisive initiative to resolve the border conflict with neighbouring Eritrea', 9000000, '2019-10-11');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('843', 'The Nobel Prize in Chemistry', 'for studies of the structure and function of the ribosome', 10000000, '2009-10-07');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('866', 'The Nobel Prize in Physics', 'for the discovery of the accelerating expansion of the Universe through observations of distant supernovae', 10000000, '2011-10-04');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('199', 'The Nobel Prize in Chemistry', 'for his work on sex hormones', 148822, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('164', 'The Nobel Prize in Chemistry', 'in recognition of his services in the advancement of organic chemistry and the chemical industry, through his work on organic dyes and hydroaromatic compounds', 138089, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('185', 'The Nobel Prize in Chemistry', 'for the services rendered through his research into the constitution of the sterols and their connection with the vitamins', 156939, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('541', 'The Nobel Peace Prize', 'for being a source of inspiration to repressed people, especially in Latin America', 880000, '1980-10-27');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('292', 'The Nobel Prize in Chemistry', 'for his studies of the transition states of chemical reactions using femtosecond spectroscopy', 7900000, '1999-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('853', 'The Nobel Prize in Chemistry', 'for palladium-catalyzed cross couplings in organic synthesis', 10000000, '2010-10-06');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('978', 'The Nobel Prize in Chemistry', 'for the development of lithium-ion batteries', 9000000, '2019-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('819', 'The Nobel Peace Prize', 'for their efforts to build up and disseminate greater knowledge about man-made climate change, and to lay the foundations for the measures that are needed to counteract such change', 10000000, '2007-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('729', 'The Nobel Prize in Chemistry', 'for the discovery and development of conductive polymers', 9000000, '2000-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('376', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane', 265000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('730', 'The Nobel Prize in Chemistry', 'for the discovery and development of conductive polymers', 9000000, '2000-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('11', 'The Nobel Prize in Physics', 'for his optical precision instruments and the spectroscopic and metrological investigations carried out with their aid', 138796, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('628', 'The Nobel Prize in  Literature', 'for his important literary production, which with clear-sighted earnestness illuminates the problems of the human conscience in our times', 208629, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('403', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the structural and functional organization of the cell', 550000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('26', 'The Nobel Prize in Physics', 'for his services to Theoretical Physics, and especially for his discovery of the law of the photoelectric effect', 121573, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('814', 'The Nobel Prize in Physics', 'for the discovery of Giant Magnetoresistance', 10000000, '2007-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('465', 'The Nobel Peace Prize', 'for his eminently practical administration of the Inter-Parliamentary Union', 141847, '1902-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('519', 'The Nobel Peace Prize', 'for his non-violent struggle against apartheid', 225987, '1961-10-23');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('513', 'The Nobel Peace Prize', 'for his altruism, reverence for life, and tireless humanitarian work  which has helped making the idea of brotherhood between men and nations a living one', 171135, '1953-10-30');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('332', 'The Nobel Prize in Physiology or Medicine', 'for his discoveries in connection with the biological combustion processes, with special reference to vitamin C and the catalysis of fumaric acid', 158463, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('304', 'The Nobel Prize in Physiology or Medicine', 'in recognition of the contributions to our knowledge of cell chemistry made through his work on proteins, including the nucleic substances', 140703, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('83', 'The Nobel Prize in Physics', 'for fundamental work in the field of quantum electronics, which has led to the construction of oscillators and amplifiers based on the maser-laser principle', 273000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('644', 'The Nobel Prize in  Literature', 'for the ethical force with which he has pursued the indispensable traditions of Russian literature', 400000, '1970-10-08');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('766', 'The Nobel Prize in Physics', 'for pioneering contributions to the theory of superconductors and superfluids', 10000000, '2003-10-07');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('306', 'The Nobel Prize in Physiology or Medicine', 'in recognition of his work on vascular suture and the transplantation of blood vessels and organs', 140476, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('544', 'The Nobel Peace Prize', 'for their work for disarmament and nuclear and weapon-free zones', 1150000, '1982-10-13');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('392', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the replication mechanism and the genetic structure of viruses', 375000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('479', 'The Nobel Peace Prize', 'for his effort to expose and fight what he considers to be the main cause of war, namely, the anarchy in international relations', 140695, '1911-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('450', 'The Nobel Prize in Physiology or Medicine', 'for their discovery of G-proteins and the role of these proteins in signal transduction in cells', 7000000, '1994-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('87', 'The Nobel Prize in Physics', 'for the discovery and development of optical methods for studying Hertzian resonances in atoms', 300000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('174', 'The Nobel Prize in Chemistry', 'in recognition of his work on the linkage of atoms in molecules by which he has thrown new light on earlier investigations and opened up new fields of research especially in inorganic chemistry', 143010, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('892', 'The Nobel Prize in  Literature', 'master of the contemporary short story', 8000000, '2013-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('417', 'The Nobel Prize in Physiology or Medicine', 'for the development of computer assisted tomography', 800000, '1979-10-11');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('305', 'The Nobel Prize in Physiology or Medicine', 'for his work on the dioptrics of the eye', 140695, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('300', 'The Nobel Prize in Physiology or Medicine', 'in recognition of his work on the role played by protozoa in causing diseases', 138796, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('543', 'The Nobel Peace Prize', 'for their work for disarmament and nuclear and weapon-free zones', 1150000, '1982-10-13');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('882', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for the theory of stable allocations and the practice of market design', 8000000, '2012-10-15');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('719', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for his contributions to welfare economics', 7600000, '1998-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('590', 'The Nobel Prize in  Literature', 'in recognition of his brilliant literary achievements, characterized as they are by a nobility of style, a profound human sympathy, grace, and a true Gallic temperament', 121573, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('360', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning heart catheterization and pathological changes in the circulatory system', 200123, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('849', 'The Nobel Prize in Physics', 'for groundbreaking experiments regarding the two-dimensional material graphene', 10000000, '2010-10-05');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('618', 'The Nobel Prize in  Literature', 'for his comprehensive and artistically significant writings, in which human problems and conditions have been presented with a fearless love of truth and keen psychological insight', 146115, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('381', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning genetic control of enzyme and virus synthesis', 282000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('534', 'The Nobel Peace Prize', 'for his struggle for human rights in the Soviet Union, for disarmament and cooperation between all nations', 630000, '1975-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('377', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane', 265000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('412', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the peptide hormone production of the brain', 700000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('802', 'The Nobel Prize in Physiology or Medicine', 'for their discovery of RNA interference - gene silencing by double-stranded RNA', 10000000, '2006-10-02');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('926', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for his analysis of consumption, poverty, and welfare', 8000000, '2015-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('768', 'The Nobel Prize in Physics', 'for pioneering contributions to the theory of superconductors and superfluids', 10000000, '2003-10-07');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('101', 'The Nobel Prize in Physics', 'for their pioneering research in radio astrophysics: Ryle for his observations and inventions, in particular of the aperture synthesis technique, and Hewish for his decisive role in the discovery of pulsars', 550000, '1974-10-15');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('538', 'The Nobel Peace Prize', 'for jointly having negotiated peace between Egypt and Israel in 1978', 725000, '1978-10-27');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('214', 'The Nobel Prize in Chemistry', 'for their invention of partition chromatography', 171135, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('311', 'The Nobel Prize in Physiology or Medicine', 'for his discovery relating to the production of heat in the muscle', 122483, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('891', 'The Nobel Prize in Chemistry', 'for the development of multiscale models for complex chemical systems', 8000000, '2013-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('490', 'The Nobel Peace Prize', 'for their crucial role in bringing about the Locarno Treaty', 116960, '1926-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('208', 'The Nobel Prize in Chemistry', 'for his research on electrophoresis and adsorption analysis, especially for his discoveries concerning the complex nature of the serum proteins', 159773, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('111', 'The Nobel Prize in Physics', 'for their discovery of cosmic microwave background radiation', 725000, '1978-10-17');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('960', 'The Nobel Prize in Physics', 'for the optical tweezers and their application to biological systems', 9000000, '2018-10-02');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('920', 'The Nobel Prize in Physics', 'for the discovery of neutrino oscillations, which shows that neutrinos have mass', 8000000, '2015-10-06');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('33', 'The Nobel Prize in Physics', 'for his discovery of the effect named after him', 126501, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('186', 'The Nobel Prize in Chemistry', 'for their investigations on the fermentation of sugar and fermentative enzymes', 172760, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('499', 'The Nobel Peace Prize', 'for his untiring struggle and his courageous efforts as Chairman of the League of Nations Disarmament Conference 1931-34', 162608, '1934-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('368', 'The Nobel Prize in Physiology or Medicine', 'for their discovery of the mechanisms in the biological synthesis of ribonucleic acid and deoxyribonucleic acid', 220678, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('119', 'The Nobel Prize in Physics', 'for their contribution to the development of laser spectroscopy', 1000000, '1981-10-19');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('203', 'The Nobel Prize in Chemistry', 'for his research and inventions in agricultural and nutrition chemistry, especially for his fodder preservation method', 121333, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('722', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning signal transduction in the nervous system', 9000000, '2000-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('310', 'The Nobel Prize in Physiology or Medicine', 'for his discovery of the capillary motor regulating mechanism', 134100, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('475', 'The Nobel Peace Prize', 'for their prominent position in the international movement for peace and arbitration', 139800, '1909-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('553', 'The Nobel Peace Prize', 'for her non-violent struggle for democracy and human rights', 6000000, '1991-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('780', 'The Nobel Prize in Chemistry', 'for the discovery of ubiquitin-mediated protein degradation', 10000000, '2004-10-06');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('923', 'The Nobel Prize in Chemistry', 'for mechanistic studies of DNA repair', 8000000, '2015-10-07');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('845', 'The Nobel Peace Prize', 'for his extraordinary efforts to strengthen international diplomacy and cooperation between peoples', 10000000, '2009-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('428', 'The Nobel Prize in Physiology or Medicine', 'for her discovery of mobile genetic elements', 1500000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('942', 'The Nobel Prize in Physics', 'for decisive contributions to the LIGO detector and the observation of gravitational waves', 9000000, '2017-10-03');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('789', 'The Nobel Prize in Physiology or Medicine', 'for their discovery of the bacterium <i>Helicobacter pylori</i> and its role in gastritis and peptic ulcer disease', 10000000, '2005-10-03');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('743', 'The Nobel Prize in Chemistry', 'for his work on chirally catalysed oxidation reactions', 10000000, '2001-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('409', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning new mechanisms for the origin and dissemination of infectious diseases', 681000, '1976-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('419', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning genetically determined structures on the cell surface that regulate immunological reactions', 880000, '1980-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('103', 'The Nobel Prize in Physics', 'for the discovery of the connection between collective motion and particle motion in atomic nuclei and the development of the theory of the structure of the atomic nucleus based on this connection', 630000, '1975-10-17');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('936', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for their contributions to contract theory', 8000000, '2016-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('426', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning prostaglandins and related biologically active substances', 1150000, '1982-10-11');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('933', 'The Nobel Prize in Chemistry', 'for the design and synthesis of molecular machines', 8000000, '2016-10-05');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('345', 'The Nobel Prize in Physiology or Medicine', 'for his discovery of the part played by the hormone of the anterior pituitary lobe in the metabolism of sugar', 146115, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('445', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the function of single ion channels in cells', 6000000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('468', 'The Nobel Peace Prize', 'for her audacity to oppose the horrors of war', 138089, '1905-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('689', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for their pathbreaking contribution to the theory of international trade and international capital movements', 700000, '1977-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('145', 'The Nobel Prize in Physics', 'for the development of neutron spectroscopy', 7000000, '1994-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('621', 'The Nobel Prize in  Literature', 'in recognition of his varied and significant writings in which he champions humanitarian ideals and freedom of thought', 164304, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('535', 'The Nobel Peace Prize', 'for the courageous efforts in founding a movement to put an end to the violent conflict in Northern Ireland', 681000, '1977-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('572', 'The Nobel Prize in  Literature', 'as a tribute to his noble, magnificent and versatile poetry, which has always been distinguished by both the freshness of its inspiration and the rare purity of its spirit', 141358, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('937', 'The Nobel Prize in  Literature', 'for having created new poetic expressions within the great American song tradition', 8000000, '2016-10-13');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('629', 'The Nobel Prize in  Literature', 'for his important achievement both in contemporary lyrical poetry and in the field of the great Russian epic tradition', 214559, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('99', 'The Nobel Prize in Physics', 'for his theoretical predictions of the properties of a supercurrent through a tunnel barrier, in particular those phenomena which are generally known as the Josephson effects', 510000, '1973-10-23');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('879', 'The Nobel Prize in Chemistry', 'for studies of G-protein-coupled receptors', 8000000, '2012-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('865', 'The Nobel Prize in Physics', 'for the discovery of the accelerating expansion of the Universe through observations of distant supernovae', 10000000, '2011-10-04');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('861', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the activation of innate immunity', 10000000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('261', 'The Nobel Prize in Chemistry', 'for his development of methodology for chemical synthesis on a solid matrix', 1650000, '1984-10-17');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('105', 'The Nobel Prize in Physics', 'for their pioneering work in the discovery of a heavy elementary particle of a new kind', 681000, '1976-10-18');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('34', 'The Nobel Prize in Physics', 'for his method of making the paths of electrically charged particles visible by condensation of vapour', 126501, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('298', 'The Nobel Prize in Physiology or Medicine', 'in recognition of their work on the structure of the nervous system', 138536, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('666', 'The Nobel Prize in  Literature', 'for a rich and intensive prose, which with restrained compassion forms a challenging vision of mans vulnerability', 3000000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('189', 'The Nobel Prize in Chemistry', 'in recognition of their contributions to the invention and development of chemical high pressure methods', 173206, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('343', 'The Nobel Prize in Physiology or Medicine', 'for their discovery of the course of the catalytic conversion of glycogen', 146115, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('43', 'The Nobel Prize in Physics', 'for his discovery of the positron', 159850, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('588', 'The Nobel Prize in  Literature', 'in special appreciation of his epic, <I>Olympian Spring</I>', 133127, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('500', 'The Nobel Peace Prize', 'for his burning love for freedom of thought and expression and his valuable contribution to the cause of peace', 159917, '1936-11-24');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('740', 'The Nobel Prize in Physics', 'for the achievement of Bose-Einstein condensation in dilute gases of alkali atoms, and for early fundamental studies of the properties of the condensates', 10000000, '2001-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('124', 'The Nobel Prize in Physics', 'for their decisive contributions to the large project, which led to the discovery of the field particles W and Z, communicators of weak interaction', 1650000, '1984-10-17');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('562', 'The Nobel Peace Prize', 'for their work towards a just and peaceful solution to the conflict in East Timor', 7400000, '1996-10-11');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('501', 'The Nobel Peace Prize', 'for his role as father of the Argentine Antiwar Pact of 1933, which he also used as a means to mediate peace between Paraguay and Bolivia in 1935', 159850, '1936-11-24');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('836', 'The Nobel Prize in Physiology or Medicine', 'for the discovery of how chromosomes are protected by telomeres and the enzyme telomerase', 10000000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('55', 'The Nobel Prize in Physics', 'for his development of the photographic method of studying nuclear processes and his discoveries regarding mesons made with this method', 164304, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('431', 'The Nobel Prize in Physiology or Medicine', 'for theories concerning the specificity in development and control of the immune system and the discovery of the principle for production of monoclonal antibodies', 1650000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('384', 'The Nobel Prize in Physiology or Medicine', 'for his discoveries concerning hormonal treatment of prostatic cancer', 300000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('25', 'The Nobel Prize in Physics', 'in recognition of the service he has rendered to precision measurements in Physics by his discovery of anomalies in nickel steel alloys', 134100, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('489', 'The Nobel Peace Prize', 'for his crucial role in bringing about the Dawes Plan', 118165, '1926-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('22', 'The Nobel Prize in Physics', 'for his discovery of the characteristic R&ouml;ntgen radiation of the elements', 133823, '1918-11-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('81', 'The Nobel Prize in Physics', 'for fundamental work in the field of quantum electronics, which has led to the construction of oscillators and amplifiers based on the maser-laser principle', 273000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('269', 'The Nobel Prize in Chemistry', 'for their development and use of molecules with structure-specific interactions of high selectivity', 2175000, '1987-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('838', 'The Nobel Prize in Physics', 'for groundbreaking achievements concerning the transmission of light in fibers for optical communication', 10000000, '2009-10-06');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('318', 'The Nobel Prize in Physiology or Medicine', 'for his work on typhus', 156939, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('307', 'The Nobel Prize in Physiology or Medicine', 'in recognition of his work on anaphylaxis', 143010, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('68', 'The Nobel Prize in Physics', 'for their penetrating investigation of the so-called parity laws which has led to important discoveries regarding the elementary particles', 208629, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('319', 'The Nobel Prize in Physiology or Medicine', 'for his discovery of the antineuritic vitamin', 172760, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('241', 'The Nobel Prize in Chemistry', 'for his work on ribonuclease, especially concerning the connection between the amino acid sequence and the biologically active conformation', 480000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('404', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the structural and functional organization of the cell', 550000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('486', 'The Nobel Peace Prize', 'for their lifelong contributions to the cause of peace and organized internationalism', 121573, '1921-12-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('453', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning the genetic control of early embryonic development', 7200000, '1995-10-09');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('858', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for their analysis of markets with search frictions', 10000000, '2010-10-11');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('873', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for their empirical research on cause and effect in the macroeconomy', 10000000, '2011-10-10');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('153', 'The Nobel Prize in Physics', 'for development of methods to cool and trap atoms with laser light', 7500000, '1997-10-15');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('662', 'The Nobel Prize in  Literature', 'who in his novel combines the poets and the painters creativeness with a deepened awareness of time in the depiction of the human condition', 1800000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('146', 'The Nobel Prize in Physics', 'for the development of the neutron diffraction technique', 7000000, '1994-10-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('44', 'The Nobel Prize in Physics', 'for their experimental discovery of the diffraction of electrons by crystals', 158463, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('772', 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel', 'for methods of analyzing economic time series with common trends (cointegration)', 10000000, '2003-10-08');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('505', 'The Nobel Peace Prize', 'for his indefatigable work for international understanding and his pivotal role in establishing the United Nations', 121333, '1945-11-12');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('333', 'The Nobel Prize in Physiology or Medicine', 'for the discovery of the role played by the sinus and aortic mechanisms in the regulation of respiration', 155077, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('803', 'The Nobel Prize in Physiology or Medicine', 'for their discovery of RNA interference - gene silencing by double-stranded RNA', 10000000, '2006-10-02');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('657', 'The Nobel Prize in  Literature', 'who with uncompromising clear-sightedness voices mans exposed condition in a world of severe conflicts', 880000, 'nan');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('410', 'The Nobel Prize in Physiology or Medicine', 'for their discoveries concerning new mechanisms for the origin and dissemination of infectious diseases', 681000, '1976-10-14');
INSERT INTO Prize (Id, prizeName, description, amountAwarded, dateAwarded) VALUES ('520', 'The Nobel Peace Prize', 'for developing the UN into an effective and constructive international organization, capable of giving life to the principles and aims expressed in the UN Charter', 250233, '1961-10-23');
INSERT INTO Laureate (Id) VALUES ('745');
INSERT INTO Laureate (Id) VALUES ('102');
INSERT INTO Laureate (Id) VALUES ('779');
INSERT INTO Laureate (Id) VALUES ('259');
INSERT INTO Laureate (Id) VALUES ('114');
INSERT INTO Laureate (Id) VALUES ('982');
INSERT INTO Laureate (Id) VALUES ('981');
INSERT INTO Laureate (Id) VALUES ('843');
INSERT INTO Laureate (Id) VALUES ('866');
INSERT INTO Laureate (Id) VALUES ('199');
INSERT INTO Laureate (Id) VALUES ('164');
INSERT INTO Laureate (Id) VALUES ('185');
INSERT INTO Laureate (Id) VALUES ('541');
INSERT INTO Laureate (Id) VALUES ('292');
INSERT INTO Laureate (Id) VALUES ('853');
INSERT INTO Laureate (Id) VALUES ('978');
INSERT INTO Laureate (Id) VALUES ('819');
INSERT INTO Laureate (Id) VALUES ('729');
INSERT INTO Laureate (Id) VALUES ('376');
INSERT INTO Laureate (Id) VALUES ('730');
INSERT INTO Laureate (Id) VALUES ('11');
INSERT INTO Laureate (Id) VALUES ('628');
INSERT INTO Laureate (Id) VALUES ('403');
INSERT INTO Laureate (Id) VALUES ('26');
INSERT INTO Laureate (Id) VALUES ('814');
INSERT INTO Laureate (Id) VALUES ('465');
INSERT INTO Laureate (Id) VALUES ('519');
INSERT INTO Laureate (Id) VALUES ('513');
INSERT INTO Laureate (Id) VALUES ('332');
INSERT INTO Laureate (Id) VALUES ('304');
INSERT INTO Laureate (Id) VALUES ('83');
INSERT INTO Laureate (Id) VALUES ('644');
INSERT INTO Laureate (Id) VALUES ('766');
INSERT INTO Laureate (Id) VALUES ('306');
INSERT INTO Laureate (Id) VALUES ('544');
INSERT INTO Laureate (Id) VALUES ('392');
INSERT INTO Laureate (Id) VALUES ('479');
INSERT INTO Laureate (Id) VALUES ('450');
INSERT INTO Laureate (Id) VALUES ('87');
INSERT INTO Laureate (Id) VALUES ('174');
INSERT INTO Laureate (Id) VALUES ('892');
INSERT INTO Laureate (Id) VALUES ('417');
INSERT INTO Laureate (Id) VALUES ('305');
INSERT INTO Laureate (Id) VALUES ('300');
INSERT INTO Laureate (Id) VALUES ('543');
INSERT INTO Laureate (Id) VALUES ('882');
INSERT INTO Laureate (Id) VALUES ('719');
INSERT INTO Laureate (Id) VALUES ('590');
INSERT INTO Laureate (Id) VALUES ('360');
INSERT INTO Laureate (Id) VALUES ('849');
INSERT INTO Laureate (Id) VALUES ('618');
INSERT INTO Laureate (Id) VALUES ('381');
INSERT INTO Laureate (Id) VALUES ('534');
INSERT INTO Laureate (Id) VALUES ('377');
INSERT INTO Laureate (Id) VALUES ('412');
INSERT INTO Laureate (Id) VALUES ('802');
INSERT INTO Laureate (Id) VALUES ('926');
INSERT INTO Laureate (Id) VALUES ('768');
INSERT INTO Laureate (Id) VALUES ('101');
INSERT INTO Laureate (Id) VALUES ('538');
INSERT INTO Laureate (Id) VALUES ('214');
INSERT INTO Laureate (Id) VALUES ('311');
INSERT INTO Laureate (Id) VALUES ('891');
INSERT INTO Laureate (Id) VALUES ('490');
INSERT INTO Laureate (Id) VALUES ('208');
INSERT INTO Laureate (Id) VALUES ('111');
INSERT INTO Laureate (Id) VALUES ('960');
INSERT INTO Laureate (Id) VALUES ('920');
INSERT INTO Laureate (Id) VALUES ('33');
INSERT INTO Laureate (Id) VALUES ('186');
INSERT INTO Laureate (Id) VALUES ('499');
INSERT INTO Laureate (Id) VALUES ('368');
INSERT INTO Laureate (Id) VALUES ('119');
INSERT INTO Laureate (Id) VALUES ('203');
INSERT INTO Laureate (Id) VALUES ('722');
INSERT INTO Laureate (Id) VALUES ('310');
INSERT INTO Laureate (Id) VALUES ('475');
INSERT INTO Laureate (Id) VALUES ('553');
INSERT INTO Laureate (Id) VALUES ('780');
INSERT INTO Laureate (Id) VALUES ('923');
INSERT INTO Laureate (Id) VALUES ('845');
INSERT INTO Laureate (Id) VALUES ('428');
INSERT INTO Laureate (Id) VALUES ('942');
INSERT INTO Laureate (Id) VALUES ('789');
INSERT INTO Laureate (Id) VALUES ('743');
INSERT INTO Laureate (Id) VALUES ('409');
INSERT INTO Laureate (Id) VALUES ('419');
INSERT INTO Laureate (Id) VALUES ('103');
INSERT INTO Laureate (Id) VALUES ('936');
INSERT INTO Laureate (Id) VALUES ('426');
INSERT INTO Laureate (Id) VALUES ('933');
INSERT INTO Laureate (Id) VALUES ('345');
INSERT INTO Laureate (Id) VALUES ('445');
INSERT INTO Laureate (Id) VALUES ('468');
INSERT INTO Laureate (Id) VALUES ('689');
INSERT INTO Laureate (Id) VALUES ('145');
INSERT INTO Laureate (Id) VALUES ('621');
INSERT INTO Laureate (Id) VALUES ('535');
INSERT INTO Laureate (Id) VALUES ('572');
INSERT INTO Laureate (Id) VALUES ('937');
INSERT INTO Laureate (Id) VALUES ('629');
INSERT INTO Laureate (Id) VALUES ('99');
INSERT INTO Laureate (Id) VALUES ('879');
INSERT INTO Laureate (Id) VALUES ('865');
INSERT INTO Laureate (Id) VALUES ('861');
INSERT INTO Laureate (Id) VALUES ('261');
INSERT INTO Laureate (Id) VALUES ('105');
INSERT INTO Laureate (Id) VALUES ('34');
INSERT INTO Laureate (Id) VALUES ('298');
INSERT INTO Laureate (Id) VALUES ('666');
INSERT INTO Laureate (Id) VALUES ('189');
INSERT INTO Laureate (Id) VALUES ('343');
INSERT INTO Laureate (Id) VALUES ('43');
INSERT INTO Laureate (Id) VALUES ('588');
INSERT INTO Laureate (Id) VALUES ('500');
INSERT INTO Laureate (Id) VALUES ('740');
INSERT INTO Laureate (Id) VALUES ('124');
INSERT INTO Laureate (Id) VALUES ('562');
INSERT INTO Laureate (Id) VALUES ('501');
INSERT INTO Laureate (Id) VALUES ('836');
INSERT INTO Laureate (Id) VALUES ('55');
INSERT INTO Laureate (Id) VALUES ('431');
INSERT INTO Laureate (Id) VALUES ('384');
INSERT INTO Laureate (Id) VALUES ('25');
INSERT INTO Laureate (Id) VALUES ('489');
INSERT INTO Laureate (Id) VALUES ('22');
INSERT INTO Laureate (Id) VALUES ('81');
INSERT INTO Laureate (Id) VALUES ('269');
INSERT INTO Laureate (Id) VALUES ('838');
INSERT INTO Laureate (Id) VALUES ('318');
INSERT INTO Laureate (Id) VALUES ('307');
INSERT INTO Laureate (Id) VALUES ('68');
INSERT INTO Laureate (Id) VALUES ('319');
INSERT INTO Laureate (Id) VALUES ('241');
INSERT INTO Laureate (Id) VALUES ('404');
INSERT INTO Laureate (Id) VALUES ('486');
INSERT INTO Laureate (Id) VALUES ('453');
INSERT INTO Laureate (Id) VALUES ('858');
INSERT INTO Laureate (Id) VALUES ('873');
INSERT INTO Laureate (Id) VALUES ('153');
INSERT INTO Laureate (Id) VALUES ('662');
INSERT INTO Laureate (Id) VALUES ('146');
INSERT INTO Laureate (Id) VALUES ('44');
INSERT INTO Laureate (Id) VALUES ('772');
INSERT INTO Laureate (Id) VALUES ('505');
INSERT INTO Laureate (Id) VALUES ('333');
INSERT INTO Laureate (Id) VALUES ('803');
INSERT INTO Laureate (Id) VALUES ('657');
INSERT INTO Laureate (Id) VALUES ('410');
INSERT INTO Laureate (Id) VALUES ('520');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('745', 'A. Michael', 'Spence', 'male', '1943-00-00');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('102', 'Aage N.', 'Bohr', 'male', '1922-06-19');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('779', 'Aaron', 'Ciechanover', 'male', '1947-10-01');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('259', 'Aaron', 'Klug', 'male', '1926-08-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('114', 'Abdus', 'Salam', 'male', '1926-01-29');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('982', 'Abhijit', 'Banerjee', 'male', '1961-02-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('981', 'Abiy', 'Ahmed Ali', 'male', '1976-08-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('843', 'Ada E.', 'Yonath', 'female', '1939-06-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('866', 'Adam G.', 'Riess', 'male', '1969-12-16');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('199', 'Adolf', 'Butenandt', 'male', '1903-03-24');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('164', 'Adolf', 'von Baeyer', 'male', '1835-10-31');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('185', 'Adolf', 'Windaus', 'male', '1876-12-25');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('541', 'Adolfo', 'Pérez Esquivel', 'male', '1931-11-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('292', 'Ahmed', 'Zewail', 'male', '1946-02-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('853', 'Akira', 'Suzuki', 'male', '1930-09-12');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('978', 'Akira', 'Yoshino', 'male', '1948-01-30');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('819', 'Al', 'Gore', 'male', '1948-03-31');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('729', 'Alan', 'Heeger', 'male', '1936-01-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('376', 'Alan', 'Hodgkin', 'male', '1914-02-05');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('730', 'Alan', 'MacDiarmid', 'male', '1927-04-14');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('11', 'Albert A.', 'Michelson', 'male', '1852-12-19');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('628', 'Albert', 'Camus', 'male', '1913-11-07');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('403', 'Albert', 'Claude', 'male', '1898-08-24');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('26', 'Albert', 'Einstein', 'male', '1879-03-14');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('814', 'Albert', 'Fert', 'male', '1938-03-07');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('465', 'Albert', 'Gobat', 'male', '1843-05-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('519', 'Albert', 'Luthuli', 'male', '1898-00-00');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('513', 'Albert', 'Schweitzer', 'male', '1875-01-14');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('332', 'Albert', 'Szent-Györgyi', 'male', '1893-09-16');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('304', 'Albrecht', 'Kossel', 'male', '1853-09-16');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('83', 'Aleksandr M.', 'Prokhorov', 'male', '1916-07-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('644', 'Alexandr', 'Solzhenitsyn', 'male', '1918-12-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('766', 'Alexei', 'Abrikosov', 'male', '1928-06-25');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('306', 'Alexis', 'Carrel', 'male', '1873-06-28');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('544', 'Alfonso', 'García Robles', 'male', '1911-03-20');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('392', 'Alfred D.', 'Hershey', 'male', '1908-12-04');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('479', 'Alfred', 'Fried', 'male', '1864-11-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('450', 'Alfred G.', 'Gilman', 'male', '1941-07-01');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('87', 'Alfred', 'Kastler', 'male', '1902-05-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('174', 'Alfred', 'Werner', 'male', '1866-12-12');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('892', 'Alice', 'Munro', 'female', '1931-07-10');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('417', 'Allan M.', 'Cormack', 'male', '1924-02-23');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('305', 'Allvar', 'Gullstrand', 'male', '1862-06-05');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('300', 'Alphonse', 'Laveran', 'male', '1845-06-18');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('543', 'Alva', 'Myrdal', 'female', '1902-01-31');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('882', 'Alvin E.', 'Roth', 'male', '1951-12-18');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('719', 'Amartya', 'Sen', 'male', '1933-11-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('590', 'Anatole', 'France', 'male', '1844-04-16');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('360', 'André F.', 'Cournand', 'male', '1895-09-24');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('849', 'Andre', 'Geim', 'male', '1958-10-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('618', 'André', 'Gide', 'male', '1869-11-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('381', 'André', 'Lwoff', 'male', '1902-05-08');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('534', 'Andrei', 'Sakharov', 'male', '1921-05-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('377', 'Andrew', 'Huxley', 'male', '1917-11-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('412', 'Andrew V.', 'Schally', 'male', '1926-11-30');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('802', 'Andrew Z.', 'Fire', 'male', '1959-04-27');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('926', 'Angus', 'Deaton', 'male', '1945-10-19');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('768', 'Anthony J.', 'Leggett', 'male', '1938-03-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('101', 'Antony', 'Hewish', 'male', '1924-05-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('538', 'Anwar', 'al-Sadat', 'male', '1918-12-25');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('214', 'Archer J.P.', 'Martin', 'male', '1910-03-01');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('311', 'Archibald V.', 'Hill', 'male', '1886-09-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('891', 'Arieh', 'Warshel', 'male', '1940-11-20');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('490', 'Aristide', 'Briand', 'male', '1862-03-28');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('208', 'Arne', 'Tiselius', 'male', '1902-08-10');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('111', 'Arno', 'Penzias', 'male', '1933-04-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('960', 'Arthur', 'Ashkin', 'male', '1922-09-02');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('920', 'Arthur B.', 'McDonald', 'male', '1943-08-29');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('33', 'Arthur H.', 'Compton', 'male', '1892-09-10');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('186', 'Arthur', 'Harden', 'male', '1865-10-12');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('499', 'Arthur', 'Henderson', 'male', '1863-09-13');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('368', 'Arthur', 'Kornberg', 'male', '1918-03-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('119', 'Arthur L.', 'Schawlow', 'male', '1921-05-05');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('203', 'Artturi', 'Virtanen', 'male', '1895-01-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('722', 'Arvid', 'Carlsson', 'male', '1923-01-25');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('310', 'August', 'Krogh', 'male', '1874-11-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('475', 'Auguste', 'Beernaert', 'male', '1829-07-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('553', 'Aung San Suu Kyi', 'nan', 'female', '1945-06-19');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('780', 'Avram', 'Hershko', 'male', '1937-12-31');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('923', 'Aziz', 'Sancar', 'male', '1946-09-08');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('845', 'Barack', 'Obama', 'male', '1961-08-04');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('428', 'Barbara', 'McClintock', 'female', '1902-06-16');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('942', 'Barry C.', 'Barish', 'male', '1936-01-27');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('789', 'Barry J.', 'Marshall', 'male', '1951-09-30');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('743', 'Barry', 'Sharpless', 'male', '1941-04-28');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('409', 'Baruch S.', 'Blumberg', 'male', '1925-07-28');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('419', 'Baruj', 'Benacerraf', 'male', '1920-10-29');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('103', 'Ben R.', 'Mottelson', 'male', '1926-07-09');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('936', 'Bengt', 'Holmström', 'male', '1949-04-18');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('426', 'Bengt I.', 'Samuelsson', 'male', '1934-05-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('933', 'Bernard L.', 'Feringa', 'male', '1951-05-18');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('345', 'Bernardo', 'Houssay', 'male', '1887-04-10');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('445', 'Bert', 'Sakmann', 'male', '1942-06-12');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('468', 'Bertha', 'von Suttner', 'female', '1843-06-09');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('689', 'Bertil', 'Ohlin', 'male', '1899-04-23');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('145', 'Bertram N.', 'Brockhouse', 'male', '1918-07-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('621', 'Bertrand', 'Russell', 'male', '1872-05-18');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('535', 'Betty', 'Williams', 'female', '1943-05-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('572', 'Bjørnstjerne', 'Bjørnson', 'male', '1832-12-08');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('937', 'Bob', 'Dylan', 'male', '1941-05-24');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('629', 'Boris', 'Pasternak', 'male', '1890-02-10');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('99', 'Brian D.', 'Josephson', 'male', '1940-01-04');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('879', 'Brian', 'Kobilka', 'male', '1955-05-30');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('865', 'Brian P.', 'Schmidt', 'male', '1967-02-24');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('861', 'Bruce A.', 'Beutler', 'male', '1957-12-29');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('261', 'Bruce', 'Merrifield', 'male', '1921-07-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('105', 'Burton', 'Richter', 'male', '1931-03-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('34', 'C.T.R.', 'Wilson', 'male', '1869-02-14');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('298', 'Camillo', 'Golgi', 'male', '1843-07-07');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('666', 'Camilo José', 'Cela', 'male', '1916-05-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('189', 'Carl', 'Bosch', 'male', '1874-08-27');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('343', 'Carl', 'Cori', 'male', '1896-12-05');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('43', 'Carl D.', 'Anderson', 'male', '1905-09-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('588', 'Carl', 'Spitteler', 'male', '1845-04-24');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('500', 'Carl', 'von Ossietzky', 'male', '1889-10-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('740', 'Carl', 'Wieman', 'male', '1951-03-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('124', 'Carlo', 'Rubbia', 'male', '1934-03-31');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('562', 'Carlos Filipe Ximenes', 'Belo', 'male', '1948-02-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('501', 'Carlos', 'Saavedra Lamas', 'male', '1878-11-01');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('836', 'Carol W.', 'Greider', 'female', '1961-04-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('55', 'Cecil', 'Powell', 'male', '1903-12-05');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('431', 'César', 'Milstein', 'male', '1927-10-08');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('384', 'Charles B.', 'Huggins', 'male', '1901-09-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('25', 'Charles Edouard', 'Guillaume', 'male', '1861-02-15');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('489', 'Charles G.', 'Dawes', 'male', '1865-08-27');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('22', 'Charles Glover', 'Barkla', 'male', '1877-06-07');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('81', 'Charles H.', 'Townes', 'male', '1915-07-28');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('269', 'Charles J.', 'Pedersen', 'male', '1904-10-03');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('838', 'Charles K.', 'Kao', 'male', '1933-11-04');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('318', 'Charles', 'Nicolle', 'male', '1866-09-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('307', 'Charles', 'Richet', 'male', '1850-08-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('68', 'Chen Ning', 'Yang', 'male', '1922-09-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('319', 'Christiaan', 'Eijkman', 'male', '1858-08-11');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('241', 'Christian', 'Anfinsen', 'male', '1916-03-26');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('404', 'Christian', 'de Duve', 'male', '1917-10-02');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('486', 'Christian', 'Lange', 'male', '1869-09-17');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('453', 'Christiane', 'Nüsslein-Volhard', 'female', '1942-10-20');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('858', 'Christopher A.', 'Pissarides', 'male', '1948-02-20');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('873', 'Christopher A.', 'Sims', 'male', '1942-10-21');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('153', 'Claude', 'Cohen-Tannoudji', 'male', '1933-04-01');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('662', 'Claude', 'Simon', 'male', '1913-10-10');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('146', 'Clifford G.', 'Shull', 'male', '1915-09-23');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('44', 'Clinton', 'Davisson', 'male', '1881-10-22');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('772', 'Clive W.J.', 'Granger', 'male', '1934-09-04');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('505', 'Cordell', 'Hull', 'male', '1871-10-02');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('333', 'Corneille', 'Heymans', 'male', '1892-03-28');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('803', 'Craig C.', 'Mello', 'male', '1960-10-19');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('657', 'Czeslaw', 'Milosz', 'male', '1911-06-30');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('410', 'D. Carleton', 'Gajdusek', 'male', '1923-09-09');
INSERT INTO Individual (Id, firstName, lastName, gender, birthDate) VALUES ('520', 'Dag', 'Hammarskjöld', 'male', '1905-07-29');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('745', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('102', 'Denmark', 'Denmark');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('779', 'British Protectorate of Palestine', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('259', 'Lithuania', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('114', 'India', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('982', 'India', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('981', 'Ethiopia', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('843', 'British Mandate of Palestine', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('866', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('199', 'Germany', 'Germany');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('164', 'Prussia', 'Germany');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('185', 'Germany', 'West Germany');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('541', 'Argentina', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('292', 'Egypt', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('853', 'Japan', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('978', 'Japan', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('819', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('729', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('376', 'United Kingdom', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('730', 'New Zealand', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('11', 'Prussia', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('628', 'French Algeria', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('403', 'Belgium', 'Belgium');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('26', 'Germany', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('814', 'France', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('465', 'Switzerland', 'Switzerland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('519', 'Southern Rhodesia', 'South Africa');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('513', 'Germany', 'Gabon');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('332', 'Austria-Hungary', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('304', 'Mecklenburg', 'Germany');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('83', 'Australia', 'Russia');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('644', 'Russia', 'Russia');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('766', 'USSR', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('306', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('544', 'Mexico', 'Mexico');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('392', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('479', 'Austria', 'Austria');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('450', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('87', 'Germany', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('174', 'France', 'Switzerland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('892', 'Canada', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('417', 'South Africa', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('305', 'Sweden', 'Sweden');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('300', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('543', 'Sweden', 'Sweden');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('882', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('719', 'India', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('590', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('360', 'France', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('849', 'Russia', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('618', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('381', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('534', 'Russia', 'USSR');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('377', 'United Kingdom', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('412', 'Poland', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('802', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('926', 'Scotland', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('768', 'United Kingdom', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('101', 'United Kingdom', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('538', 'Egypt', 'Egypt');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('214', 'United Kingdom', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('311', 'United Kingdom', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('891', 'British Mandate of Palestine', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('490', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('208', 'Sweden', 'Sweden');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('111', 'Germany', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('960', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('920', 'Canada', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('33', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('186', 'United Kingdom', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('499', 'Scotland', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('368', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('119', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('203', 'Russian Empire', 'Finland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('722', 'Sweden', 'Sweden');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('310', 'Denmark', 'Denmark');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('475', 'Belgium', 'Switzerland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('553', 'Burma', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('780', 'Hungary', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('923', 'Turkey', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('845', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('428', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('942', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('789', 'Australia', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('743', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('409', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('419', 'Venezuela', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('103', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('936', 'Finland', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('426', 'Sweden', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('933', 'the Netherlands', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('345', 'Argentina', 'Argentina');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('445', 'Germany', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('468', 'Austrian Empire', 'Austria');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('689', 'Sweden', 'Sweden');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('145', 'Canada', 'Canada');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('621', 'United Kingdom', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('535', 'Northern Ireland', 'Northern Ireland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('572', 'Norway', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('937', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('629', 'Russia', 'Russia');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('99', 'United Kingdom', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('879', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('865', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('861', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('261', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('105', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('34', 'Scotland', 'Scotland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('298', 'Italy', 'Italy');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('666', 'Spain', 'Spain');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('189', 'Germany', 'Germany');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('343', 'Austria-Hungary', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('43', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('588', 'Switzerland', 'Switzerland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('500', 'Germany', 'Germany');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('740', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('124', 'Italy', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('562', 'East Timor', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('501', 'Argentina', 'Argentina');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('836', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('55', 'United Kingdom', 'Italy');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('431', 'Argentina', 'United Kingdom');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('384', 'Canada', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('25', 'Switzerland', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('489', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('22', 'United Kingdom', 'Scotland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('81', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('269', 'Korea', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('838', 'China', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('318', 'France', 'Tunisia');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('307', 'France', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('68', 'China', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('319', 'the Netherlands', 'the Netherlands');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('241', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('404', 'United Kingdom', 'Belgium');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('486', 'Norway', 'Norway');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('453', 'Germany', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('858', 'Cyprus', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('873', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('153', 'French Algeria', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('662', 'Madagascar', 'France');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('146', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('44', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('772', 'United Kingdom', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('505', 'USA', 'USA');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('333', 'Belgium', 'Belgium');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('803', 'USA', 'nan');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('657', 'Russian Empire', 'Poland');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('410', 'USA', 'Norway');
INSERT INTO Country (Id, birthCountry, deathCountry) VALUES ('520', 'Sweden', 'Northern Rhodesia');
